Add CLI with Cliffy
restake/sui-withdrawer pull request #1
Opened 2023-07-04 16:29 UTC by mllnd

2023-07-05 11:21 UTC, mikroskeem requested changes

2023-07-05 11:21 UTC, mikroskeem commented on bin/withdrawer.ts
> +    provider: string;
```suggestion
    provider: "vault" | "plain-text";
```

2023-07-05 11:21 UTC, mikroskeem commented on bin/withdrawer.ts
> +                        await next("keypair");
```suggestion
                        await next("plain-text");
```

? Or do we have three different values?

2023-07-06 16:16 UTC, mllnd commented on bin/withdrawer.ts
> +                        await next("keypair");
N/A

2023-07-10 17:58 UTC, mikroskeem requested changes

2023-07-10 17:58 UTC, mikroskeem commented on bin/withdrawer.ts
> +const getSigner = async (prompt: Prompt | SendPrompt): Promise<RawSigner> => {
```suggestion
const getSigner = async (prompt: Prompt): Promise<RawSigner> => {
```

`SendPrompt` fields are not used here

2023-07-10 17:58 UTC, mikroskeem commented on bin/withdrawer.ts
> +let sendPrompt: SendPrompt;
Why do you have those as global variables? Could pass in necessary parameters to withdraw & send functions directly. Furthermore those should be `Prompt | undefined` to be correct.

2023-07-10 17:58 UTC, mikroskeem commented on bin/withdrawer.ts
> +const send = async () => {
```suggestion
const send = async (sendPrompt: SendPrompt) => {
```

2023-07-10 17:58 UTC, mikroskeem commented on bin/withdrawer.ts
> +const withdraw = async () => {
```suggestion
const withdraw = async (withdrawPrompt: Prompt) => {
```

2023-07-10 17:58 UTC, mikroskeem commented on bin/withdrawer.ts
> +};
```suggestion
type Prompt = {
    provider: "vault" | "plain-text";
    path: string | undefined;
    key: string | undefined;
    keypair: string | undefined;
};

type VaultPrompt = Prompt & {
   provider: "vault";
   path: string;
   key: string;
};

type PlaintextPrompt = Prompt & {
    provider: "plain-text";
    keypair: string;
};

function isVaultPrompt(p: Prompt): p is VaultPrompt {
    return p.provider === "vault";
}

function isPlaintextPrompt(p: Prompt): p is PlaintextPrompt {
    return p.provider === "plain-text";
}
```

2023-07-10 17:58 UTC, mikroskeem commented on bin/withdrawer.ts
> +    }
```suggestion
    if (isVaultPrompt(prompt)) {
        keypair = await getKeypair(prompt.path, prompt.key);
    } else if (isPlaintextPrompt(prompt)) {
        keypair = Ed25519Keypair.fromSecretKey(decodeKeypair(prompt.keypair));
    } else {
        throw new Error(`Unsupported provider "${prompt.provider}"`);
    }
```

2023-07-10 17:58 UTC, mikroskeem commented on bin/withdrawer.ts
> +const getPrompt = (): any => {
```suggestion
const getPrompt = <T>(): Promise<T> => {
```

2023-07-10 17:58 UTC, mikroskeem commented on bin/withdrawer.ts
> +    ]);
```suggestion
    ]) as unknown as T;
```

2023-07-10 17:58 UTC, mikroskeem commented on bin/withdrawer.ts
> +        await withdraw();
```suggestion
        await getPrompt<WithdrawPrompt>().then(withdraw);
```

2023-07-10 17:58 UTC, mikroskeem commented on bin/withdrawer.ts
> +        await send();
```suggestion
        await getPrompt<SendPrompt>().then(send);
```

2023-07-10 17:58 UTC, mikroskeem commented on sui.ts
> +    let tx: SuiTransactionBlockResponse;
```suggestion
```

2023-07-10 17:58 UTC, mikroskeem commented on sui.ts
> +        tx = await signer.signAndExecuteTransactionBlock({
```suggestion
        return await signer.signAndExecuteTransactionBlock({
```

2023-07-10 17:58 UTC, mikroskeem commented on sui.ts
> +    return tx;
```suggestion
```

2023-07-10 17:58 UTC, mikroskeem commented on vault.ts
> +        throw new Error(`Failed to login to Vault: ${e}`);
```suggestion
        throw new Error(`Failed to login to Vault`, {
            cause: e,
        });
```

2023-07-10 17:58 UTC, mikroskeem commented on vault.ts
> +        throw new Error(`Failed to read keypair from Vault: ${e}`);
```suggestion
        throw new Error(`Failed to read keypair from Vault`, {
            cause: e,
        });
```

2023-07-10 17:58 UTC, mikroskeem commented on sui.ts
> +        throw new Error(`Failed to send ${amount} SUI to ${recipient}: ${e}`);
```suggestion
        throw new Error(`Failed to send ${amount} SUI to ${recipient}`, {
            cause: e,
        });
```

2023-07-10 17:58 UTC, mikroskeem commented on sui.ts
>              throw new Error(`Failed to withdraw stake ${stake.stakedSuiId}: ${e}`);
```suggestion
            throw new Error(`Failed to withdraw stake ${stake.stakedSuiId}`, {
                cause: e,
            });
```

2023-07-11 13:02 UTC, mikroskeem approved these changes

2023-07-11 13:51 UTC, merged